# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-7a3e0b5d-98d9-4fbb-9de0-27e11a96ba53";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-fc5c8ca4-5cf8-4c4d-a0f0-d084d5e3e3f9".device = "/dev/disk/by-uuid/fc5c8ca4-5cf8-4c4d-a0f0-d084d5e3e3f9";
  boot.initrd.luks.devices."luks-7a3e0b5d-98d9-4fbb-9de0-27e11a96ba53".device = "/dev/disk/by-uuid/7a3e0b5d-98d9-4fbb-9de0-27e11a96ba53";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/ECF8-2EFD";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-fc5c8ca4-5cf8-4c4d-a0f0-d084d5e3e3f9"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
