# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-53e7672b-7861-4d33-af8b-50c94a80919b";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-53e7672b-7861-4d33-af8b-50c94a80919b".device = "/dev/disk/by-uuid/53e7672b-7861-4d33-af8b-50c94a80919b";
  boot.initrd.luks.devices."luks-00d6920d-4743-41e3-91d8-3572a99c762d".device = "/dev/disk/by-uuid/00d6920d-4743-41e3-91d8-3572a99c762d";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/BAC9-BDE6";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-00d6920d-4743-41e3-91d8-3572a99c762d"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
